---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "java-app-service"
  namespace: "default"
  labels:
    app: "java"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "java"
  type: "LoadBalancer"
  loadBalancerIP: ""
